Drop `monero-wallet-rpc` test container if errors
Previously we tried to wait longer upon errors on startup, but that did not fix the problem:

```
 May 28 05:35:01.440  INFO monero_harness: Starting wallet: bob
May 28 05:35:04.350  INFO testcontainers::core::wait_for_message: Found message after comparing 16 lines
May 28 05:35:04.409  WARN monero_harness: Monero wallet RPC emitted error error sending request for url (http://127.0.0.1:49183/json_rpc): operation was canceled: connection closed before message completed - retrying to create wallet in 2 seconds...
May 28 05:35:06.413  WARN monero_harness: Monero wallet RPC emitted error error sending request for url (http://127.0.0.1:49183/json_rpc): operation was canceled: connection closed before message completed - retrying to create wallet in 2 seconds...
May 28 05:35:08.416  WARN monero_harness: Monero wallet RPC emitted error error sending request for url (http://127.0.0.1:49183/json_rpc): operation was canceled: connection closed before message completed - retrying to create wallet in 2 seconds...
May 28 05:35:10.420  WARN monero_harness: Monero wallet RPC emitted error error sending request for url (http://127.0.0.1:49183/json_rpc): operation was canceled: connection closed before message completed - retrying to create wallet in 2 seconds...
May 28 05:35:12.424  WARN monero_harness: Monero wallet RPC emitted error error sending request for url (http://127.0.0.1:49183/json_rpc): operation was canceled: connection closed before message completed - retrying to create wallet in 2 seconds...
thread 'alice_manually_redeems_after_enc_sig_learned' panicked at 'called `Result::unwrap()` on an `Err` value: All retry attempts for creating a wallet exhausted
```

Thus we now drop the container upon error and try to spin up a new one. If the container is not up within 5 minutes we timeout.